### ISSUE TITLE
EEPROM.h is missing from the Installation files of Teensyduino 1.23

### ISSUE THREAD

**Issue by pramilo** [PaulStoffregen/EEPROM#1]
- Using Ardino IDE 1.0.6 and Teensydino 1.23
- Standard install, selected to _Install ALL Libraries_.

After installation the file EEPROM.h is missing from the folder "arduino-1.0.6\hardware\teensy\cores\teensy3"

Did the usual Sketch->Import Library->EEPROM which added the "#include <EEPROM.h>" line to the top of the file.

However when trying to compile you get a "missing EEPROM.h". After many hours trying to track down the issue, it turns out the file is actually missing in the install package.
I was finally able to track down this file, manually placed it in arduino-1.0.6\hardware\teensy\cores\teensy3 and it started compiling just fine.

BTW: tried to report the issue on your forum but the registration form doesn't work. 
The verification for human is not displayed although I keep getting an error saying I didn't complete that verification.

**Comment by PaulStoffregen** [comment]
Oh, I see what's happening.  It is installing the newer EEPROM.h, which conflicts with the older EEPROM.cpp.  It should delete the old EEPROM.cpp, but doesn't.

**Comment by PaulStoffregen** [comment]
fixed
https://github.com/PaulStoffregen/EEPROM/commit/d47cd7134d42093d796baf22adb19e56d521bd73
