### ISSUE TITLE
EEPROM Lenght

### ISSUE THREAD

**Issue by Emre-ee** [PaulStoffregen/EEPROM#6]
I added  cli() function to code line. Then, i added the  int eepromLenght = EEPROM.length() code. Then , I printed serial terminal, it came eepromLenght= 10. I use without cli(), it come eepromLenght= 1024. Why?
I didn't understand.
`#include <EEPROM.h>
void setup() {
  // put your setup code here, to run once:
cli();  
int eepromLenght = EEPROM.length();
Serial.begin(115200);
Serial.println(eepromLenght);

}

void loop() {
  // put your main code here, to run repeatedly:

}`

**Comment by PaulStoffregen** [comment]
This is the wrong place to ask question.  Use the forum.  If you ask this on the forum, clearly say which Teensy you're using!
